name: deploy

on:
    push:
        branches: 
            - "main"
jobs:
    checkout:
        runs-on: [self-hosted]
        steps:
            - name: 🛒 Checkout
              uses: actions/checkout@v2

    build:
        needs: checkout
        if: github.ref == 'refs/heads/main'
        runs-on: [self-hosted]
        
        steps:
          - name: Install dependencies
            run: npm install

          - name: build dependencies
            run: npm run build  
              
          - name: create env file
            run: |
                touch ./dist/.env
                    echo HOST = '43.200.195.138' >> ./dist/.env
                    echo DB_HOST = '43.200.195.138' >> ./dist/.env
                    echo ELASTIC_HOST = 'http://221.148.25.234:9200' >> ./dist/.env
                    echo DB_PORT = 3306 >> ./dist/.env
                    echo REDIS_PORT = 6379 >> ./dist/.env
                    echo DB_USERNAME = 'crypto-data' >> ./dist/.env
                    echo DB_PASSWD = '1207' >> ./dist/.env
                    echo DB_DATABASE = 'item_oasis' >> ./dist/.env
                    echo AWS_ACECSS_KEY_ID = 'AKIA25QHJSJLUFOJS6UC' >> ./dist/.env
                    echo AWS_SECRET_ACCESS_KEY = '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' >> ./dist/.env
                    echo AWS_BUCKET_REGION = 'ap-northeast-2' >> ./dist/.env
                    echo AWS_BUCKET_NAME = 'crypto-games-s3' >> ./dist/.env
                    echo JWT_SCRET_KEY = 'itemoasisjwtscretkey' >> ./dist/.env
                    echo REFRESH_JWT_SCRET_KEY = 'itemoasisrefreshjwtscretkey' >> ./dist/.env
                    echo PORT = '1207' >> ./dist/.env
                    echo CONTRACT_PRIVATE_KEY = '5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3' >> ./dist/.env
                    echo CONTRACT_ACCOUNT_NAME = 'eosio.item' >> ./dist/.env
                    
          - name: Copy new server to html folder
            run: |
                cp -R ./ /var/www/html/item-oasis-api

          - name: pm2 restart
            run: pm2 restart item-oasis-api 
